# Generated by Django 5.0.6 on 2024-07-06 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_item_birthday_item_date_of_birth_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='agency_employee',
            new_name='agencyEmployee',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='blood_type',
            new_name='bloodType',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='civil_status',
            new_name='civilStatus',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='date_of_birth',
            new_name='dateOfBirth',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='first_name',
            new_name='firstName',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='gsis_id',
            new_name='gsisId',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='last_name',
            new_name='lastName',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='middle_name',
            new_name='middleName',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='pag_ibig_id',
            new_name='pagIbigId',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='permanent_address',
            new_name='permanentAddress',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='philhealt_id',
            new_name='philhealtId',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='place_of_birth',
            new_name='placeOfBbirth',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='residential_address',
            new_name='residentialAddress',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='sss_no',
            new_name='sssNo',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='tin_no',
            new_name='tinNo',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='zip_code',
            new_name='zipCode',
        ),
    ]
