# Generated by Django 5.0.6 on 2024-07-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_agency_employee_item_agencyemployee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='permanentAddress',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='residentialAddress',
            field=models.TextField(default='', max_length=100),
        ),
    ]
